name: Deploy on Pull Request
on: [pull_request]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: ./Dockerfile # Specify the path to your Dockerfile

      - name: Build and push Docker image
        run: |
          docker build -t your-react-app-image .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag your-react-app-image ${{ secrets.DOCKER_REGISTRY_URL }}/your-react-app-image:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/your-react-app-image:latest

      - name: Deploy with Docker Compose
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_HOST }} "cd /var/www/html/development && docker-compose -f ./docker-compose.yml up -d"
