name: PR Release
on: [pull_request]


env:
  GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile # Specify the path to your Dockerfile

      - name: Build and push Docker image
        run: |
          docker build -t your-react-app-image .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag your-react-app-image ${{ secrets.DOCKER_REGISTRY_URL }}/your-react-app-image:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/your-react-app-image:latest

      - name: Deploy with Docker Compose
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@34.253.131.34
